# Generated by Django 5.0.3 on 2024-05-11 04:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('type', models.CharField(max_length=150)),
                ('location', models.CharField(max_length=150)),
                ('duration', models.TimeField()),
                ('category', models.CharField(max_length=150)),
                ('staff_associated', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
