# Generated by Django 5.0.3 on 2024-05-11 04:59

import utils.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, default='service_default.jpg', upload_to=utils.utils.gen_random_filename),
        ),
    ]
