# Generated by Django 5.0.3 on 2024-05-08 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('item_name', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('critical_point', models.IntegerField()),
                ('qty', models.PositiveIntegerField()),
                ('desc', models.CharField(blank=True, max_length=150)),
                ('last_restock', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='InvHis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveIntegerField()),
                ('date', models.DateField(auto_now_add=True)),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.inventory')),
            ],
        ),
    ]
