# Generated by Django 5.0.3 on 2024-05-12 16:39

import utils.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='image',
            field=models.ImageField(blank=True, default='inventory_default.jpg', upload_to=utils.utils.gen_random_filename),
        ),
    ]
