# Generated by Django 5.0.3 on 2024-04-19 05:00

import utils.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='avatar',
            field=models.ImageField(blank=True, default='default.jpg', upload_to=utils.utils.gen_random_filename),
        ),
    ]
